INSERT INTO "WZD_FNCT_INFO" (FNCT_ID, USER_ID, FNCT_NM, USER_URL, MANAGER_URL, BASIS_YN, USE_YN, MULTI_YN, FNCT_INFO, RGSDE, UPDDE)  VALUES ('enterCldrApply', 'class', '캘린더형 신청', '/enterCldrApply/{siteId}/{fnctNo}/main', '/enterCldrApply/fnctMngr/{siteId}/setupList', 'N', 'Y', 'Y', '캘린더형 신청 모듈입니다.', to_date('26/06/23','RR/MM/DD'), to_date('26/06/23','RR/MM/DD'));
Insert into WZD_FNCT_INFO_LANG (FNCT_INFO_LANG_SEQ,FNCT_ID,FNCT_LANG,FNCT_NM,RGSDE,UPDDE) values (101,'enterCldrApply','ko','캘린더형 신청',to_date('26/06/23','RR/MM/DD'),to_date('26/06/23','RR/MM/DD'));
Insert into WZD_FNCT_SKIN (SKIN_ID,FNCT_ID,SKIN_NM,SKIN_TYPE,SKIN_INFO,RGSDE,UPDDE,USER_ID,SITE_ID,USER_SKIN_YN,BASIS_YN) values ('enterCldrApply_basic_skin','enterCldrApply','캘린더형 신청','basic',null,to_date('26/06/23','RR/MM/DD'),to_date('26/06/23','RR/MM/DD'),'class',null,'N','Y');




-- ============================================================
-- 1. ADD_ENTER_CLDR_SETUP  (캘린더 신청 설정)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_SETUP (
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    SETUP_NM            VARCHAR2(200)   NOT NULL,
    USE_YN              VARCHAR2(1)     NOT NULL,
    MON_YN              VARCHAR2(1)     NOT NULL,
    TUE_YN              VARCHAR2(1)     NOT NULL,
    WED_YN              VARCHAR2(1)     NOT NULL,
    THU_YN              VARCHAR2(1)     NOT NULL,
    FRI_YN              VARCHAR2(1)     NOT NULL,
    SAT_YN              VARCHAR2(1)     NOT NULL,
    SUN_YN              VARCHAR2(1)     NOT NULL,
    COMPANION_USE_YN    VARCHAR2(1)     NOT NULL,
    TARGET_COMP_USE_YN  VARCHAR2(1)     NOT NULL,
    INTRO               CLOB,
    APPLY_TARGET        VARCHAR2(400),
    LOCATION            VARCHAR2(400),
    CONTENT             CLOB,
    RECV_START_DT       DATE,
    RECV_END_DT         DATE,
    MOD_START_DT        DATE,
    MOD_END_DT          DATE,
    POPUP_MSG           CLOB,
    PRIVACY_PURPOSE     CLOB,
    PRIVACY_ITEMS       CLOB,
    PRIVACY_PERIOD      VARCHAR2(200),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    MDFCN_DT              DATE,
    MDFCN_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_SETUP PRIMARY KEY (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_SETUP                        IS '캘린더 신청 - 설정';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.SETUP_SEQ             IS '설정 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.SETUP_NM              IS '설정명';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.USE_YN                IS '사용여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.MON_YN                IS '월요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.TUE_YN                IS '화요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.WED_YN                IS '수요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.THU_YN                IS '목요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.FRI_YN                IS '금요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.SAT_YN                IS '토요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.SUN_YN                IS '일요일 신청가능여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.COMPANION_USE_YN      IS '동반인원 사용여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.TARGET_COMP_USE_YN    IS '대상별 인원 사용여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.INTRO                 IS '소개';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.APPLY_TARGET          IS '신청대상';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.LOCATION              IS '장소';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.CONTENT               IS '내용 (에디터)';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.RECV_START_DT         IS '접수 시작일';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.RECV_END_DT           IS '접수 종료일';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.MOD_START_DT          IS '수정 시작일';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.MOD_END_DT            IS '수정 종료일';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.POPUP_MSG             IS '팝업 안내 메시지';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.PRIVACY_PURPOSE       IS '개인정보 수집·이용 목적';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.PRIVACY_ITEMS         IS '수집하는 개인정보 항목';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.PRIVACY_PERIOD        IS '개인정보 보유·이용기간';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.REG_DT                IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.REG_ID                IS '등록자 ID';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.MDFCN_DT                IS '수정일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_SETUP.MDFCN_ID                IS '수정자 ID';


-- ============================================================
-- 2. ADD_ENTER_CLDR_TIME_SLOT  (시간 슬롯)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_TIME_SLOT (
    SLOT_SEQ            NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    APPLY_TIME          VARCHAR2(10)    NOT NULL,
    LIMIT_CNT           NUMBER(10)      NOT NULL,
    SORT_NO            NUMBER(10),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    MDFCN_DT              DATE,
    MDFCN_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_TIME_SLOT PRIMARY KEY (SLOT_SEQ),
    CONSTRAINT FK_TIME_SLOT_SETUP FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_TIME_SLOT              IS '캘린더 신청 - 시간 슬롯';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.SLOT_SEQ     IS '시간 슬롯 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.SETUP_SEQ    IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.APPLY_TIME   IS '신청 시간 (HH24:MI)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.LIMIT_CNT    IS '회차별 정원 제한 인원';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.SORT_NO     IS '정렬 순서';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.REG_DT       IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.REG_ID       IS '등록자 ID';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.MDFCN_DT       IS '수정일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_TIME_SLOT.MDFCN_ID       IS '수정자 ID';


-- ============================================================
-- 3. ADD_ENTER_CLDR_TARGET_ITEM  (대상별 항목)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_TARGET_ITEM (
    ITEM_SEQ            NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    TARGET_NM           VARCHAR2(200)   NOT NULL,
    SORT_NO            NUMBER(10),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_TARGET_ITEM PRIMARY KEY (ITEM_SEQ),
    CONSTRAINT FK_TARGET_ITEM_SETUP FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_TARGET_ITEM            IS '캘린더 신청 - 대상별 항목';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.ITEM_SEQ   IS '항목 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.SETUP_SEQ  IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.TARGET_NM  IS '대상명 (예: 학부모, 1학년)';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.SORT_NO   IS '정렬 순서';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.REG_DT     IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_TARGET_ITEM.REG_ID     IS '등록자 ID';


-- ============================================================
-- 4. ADD_ENTER_CLDR_FORM_ITEM  (동적 폼 항목)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_FORM_ITEM (
    ITEM_SEQ            NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    ITEM_NM             VARCHAR2(200)   NOT NULL,
    ITEM_TYPE           VARCHAR2(30)    NOT NULL,
    REQUIRED_YN         VARCHAR2(1)     NOT NULL,
    ITEM_VALUES         CLOB,
    SYSTEM_YN           VARCHAR2(1)     NOT NULL,
    SORT_NO            NUMBER(10),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    MDFCN_DT              DATE,
    MDFCN_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_FORM_ITEM PRIMARY KEY (ITEM_SEQ),
    CONSTRAINT FK_FORM_ITEM_SETUP FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_FORM_ITEM               IS '캘린더 신청 - 동적 폼 항목';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.ITEM_SEQ      IS '항목 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.SETUP_SEQ     IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.ITEM_NM       IS '항목명';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.ITEM_TYPE     IS '항목 유형 (TEXT/Phone/Email/Radio/Checkbox/School)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.REQUIRED_YN   IS '필수여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.ITEM_VALUES   IS '선택 항목 데이터 (콤마 구분, Radio/Checkbox용)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.SYSTEM_YN     IS '시스템 고정 항목 여부 (이름/휴대전화는 Y)';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.SORT_NO      IS '정렬 순서';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.REG_DT        IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.REG_ID        IS '등록자 ID';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.MDFCN_DT        IS '수정일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_FORM_ITEM.MDFCN_ID        IS '수정자 ID';


-- ============================================================
-- 5. ADD_ENTER_CLDR_HOLIDAY  (휴일)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_HOLIDAY (
    HOLIDAY_SEQ         NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    HOLIDAY_DT          DATE            NOT NULL,
    REASON              VARCHAR2(400),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    MDFCN_DT            DATE,
    MDFCN_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_HOLIDAY PRIMARY KEY (HOLIDAY_SEQ),
    CONSTRAINT FK_HOLIDAY_SETUP FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_HOLIDAY              IS '캘린더 신청 - 휴일';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.HOLIDAY_SEQ  IS '휴일 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.SETUP_SEQ    IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.HOLIDAY_DT   IS '휴일 일자';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.REASON       IS '휴일 사유';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.REG_DT       IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.REG_ID       IS '등록자 ID';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.MDFCN_DT       IS '수정일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_HOLIDAY.MDFCN_ID       IS '수정자 ID';


-- ============================================================
-- 6. ADD_ENTER_CLDR_ATCHMNFL  (첨부파일)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_ATCHMNFL (
    ATCHMNFL_SEQ        NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    ORGINL_NM           VARCHAR2(400)   NOT NULL,
    CHANGE_NM             VARCHAR2(400)   NOT NULL,
    FILE_PATH           VARCHAR2(1000)  NOT NULL,
    FILE_SIZE           NUMBER(19),
    FILE_EXT            VARCHAR2(20),
    SORT_NO            NUMBER(10),
    REG_DT              DATE,
    REG_ID              VARCHAR2(100),
    CONSTRAINT PK_ADD_ENTER_CLDR_ATCHMNFL PRIMARY KEY (ATCHMNFL_SEQ),
    CONSTRAINT FK_ATCHMNFL_SETUP FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_ATCHMNFL               IS '캘린더 신청 - 첨부파일';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.ATCHMNFL_SEQ  IS '첨부파일 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.SETUP_SEQ     IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.ORGINL_NM     IS '원본 파일명';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.CHANGE_NM     IS '저장 파일명';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.FILE_PATH     IS '파일 저장 경로';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.FILE_SIZE     IS '파일 크기 (byte)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.FILE_EXT      IS '파일 확장자';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.SORT_NO       IS '정렬 순서';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.REG_DT        IS '등록일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_ATCHMNFL.REG_ID        IS '등록자 ID';


-- ============================================================
-- 7. ADD_ENTER_CLDR_ARTCL  (신청 본문)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_ARTCL (
    ARTCL_SEQ           NUMBER(10)      NOT NULL,
    SETUP_SEQ           NUMBER(10)      NOT NULL,
    TIME_SLOT_SEQ       NUMBER(10)      NOT NULL,
    ARTCL_DT            DATE            NOT NULL,
    ARTCL_NM            VARCHAR2(200)   NOT NULL,
    PHONE               VARCHAR2(400)   NOT NULL,   -- ARIA 암호화 저장
    EMAIL               VARCHAR2(200),
    SCHOOL_CODE         VARCHAR2(100),
    SCHOOL_NM           VARCHAR2(200),
    SCHOOL_REGION       VARCHAR2(200),
    SCHOOL_TYPE         VARCHAR2(100),
    COMPANION_CNT       NUMBER(10),
    MEAL_YN             VARCHAR2(1),
    ARTCL_STATUS        VARCHAR2(20)    NOT NULL,   -- 승인대기/승인/미승인
    DEL_YN              VARCHAR2(1)     NOT NULL,
    REG_DT              DATE,
    MDFCN_DT              DATE,
    CONSTRAINT PK_ADD_ENTER_CLDR_ARTCL PRIMARY KEY (ARTCL_SEQ),
    CONSTRAINT FK_ARTCL_SETUP     FOREIGN KEY (SETUP_SEQ)
        REFERENCES ADD_ENTER_CLDR_SETUP (SETUP_SEQ),
    CONSTRAINT FK_ARTCL_TIME_SLOT FOREIGN KEY (TIME_SLOT_SEQ)
        REFERENCES ADD_ENTER_CLDR_TIME_SLOT (SLOT_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_ARTCL                  IS '캘린더 신청 - 신청 본문';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.ARTCL_SEQ        IS '신청 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.SETUP_SEQ        IS '설정 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.TIME_SLOT_SEQ    IS '시간 슬롯 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.ARTCL_DT         IS '신청 일자';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.ARTCL_NM         IS '신청자 이름';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.PHONE            IS '휴대전화 (ARIA 암호화)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.EMAIL            IS '이메일';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.SCHOOL_CODE      IS '고교 NEIS 코드';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.SCHOOL_NM        IS '고교명';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.SCHOOL_REGION    IS '고교 지역';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.SCHOOL_TYPE      IS '고교 유형';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.COMPANION_CNT    IS '동반 인원 합계';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.MEAL_YN          IS '식사 여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.ARTCL_STATUS     IS '신청 상태 (승인대기/승인/미승인)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.DEL_YN           IS '삭제(취소) 여부 (Y/N)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.REG_DT           IS '신청 등록 일시';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL.MDFCN_DT         IS '최종 수정 일시';


-- ============================================================
-- 8. ADD_ENTER_CLDR_ARTCL_TARGET  (신청별 대상 동반인원)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_ARTCL_TARGET (
    TARGET_SEQ          NUMBER(10)      NOT NULL,
    ARTCL_SEQ           NUMBER(10)      NOT NULL,
    TARGET_ITEM_SEQ     NUMBER(10)      NOT NULL,
    COMP_CNT            NUMBER(10)      NOT NULL,
    CONSTRAINT PK_ADD_ENTER_CLDR_ARTCL_TARGET PRIMARY KEY (TARGET_SEQ),
    CONSTRAINT FK_ARTCL_TARGET_ARTCL FOREIGN KEY (ARTCL_SEQ)
        REFERENCES ADD_ENTER_CLDR_ARTCL (ARTCL_SEQ),
    CONSTRAINT FK_ARTCL_TARGET_ITEM FOREIGN KEY (TARGET_ITEM_SEQ)
        REFERENCES ADD_ENTER_CLDR_TARGET_ITEM (ITEM_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_ARTCL_TARGET                   IS '캘린더 신청 - 신청별 대상 동반인원';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_TARGET.TARGET_SEQ        IS 'SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_TARGET.ARTCL_SEQ         IS '신청 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_TARGET.TARGET_ITEM_SEQ   IS '대상 항목 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_TARGET.COMP_CNT          IS '대상별 동반 인원 수';


-- ============================================================
-- 9. ADD_ENTER_CLDR_ARTCL_ANSWER  (동적 폼 답변)
-- ============================================================
CREATE TABLE ADD_ENTER_CLDR_ARTCL_ANSWER (
    ANSWER_SEQ          NUMBER(10)      NOT NULL,
    ARTCL_SEQ           NUMBER(10)      NOT NULL,
    FORM_ITEM_SEQ       NUMBER(10)      NOT NULL,
    ANSWER_VAL          CLOB,
    CONSTRAINT PK_ADD_ENTER_CLDR_ARTCL_ANSWER PRIMARY KEY (ANSWER_SEQ),
    CONSTRAINT FK_ANSWER_ARTCL FOREIGN KEY (ARTCL_SEQ)
        REFERENCES ADD_ENTER_CLDR_ARTCL (ARTCL_SEQ),
    CONSTRAINT FK_ANSWER_FORM_ITEM FOREIGN KEY (FORM_ITEM_SEQ)
        REFERENCES ADD_ENTER_CLDR_FORM_ITEM (ITEM_SEQ)
);

COMMENT ON TABLE  ADD_ENTER_CLDR_ARTCL_ANSWER                IS '캘린더 신청 - 동적 폼 답변';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_ANSWER.ANSWER_SEQ     IS '답변 SEQ (PK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_ANSWER.ARTCL_SEQ      IS '신청 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_ANSWER.FORM_ITEM_SEQ  IS '폼 항목 SEQ (FK)';
COMMENT ON COLUMN ADD_ENTER_CLDR_ARTCL_ANSWER.ANSWER_VAL     IS '입력값';
